<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE airports [
   <!ELEMENT airports (airport*)>
      <!ELEMENT airport (name, closed)>
      <!ELEMENT name (#PCDATA)>
      <!ELEMENT closed (#PCDATA)>
]> 
 
<airports>
   <airport>
        <name>Berlín Schönefeld (SFX)</name>
        <closed></closed>
   </airport>
   <airport>
        <name>Berlín Tempelhof (THF)</name>
        <closed></closed>
    </airport>
</airports> 